package vmfs

import (
	"bytes"
	"encoding/binary"
	"io"
	"io/fs"
	"path"
	"strings"
	"testing"
	"testing/fstest"
	"time"
)

const vgText = `# Generated by LVM2
contents = "Text Format Volume Group"
version = 1

ubuntu-vg {
	id = "abc"
	seqno = 3
	extent_size = 8192		# 4 Megabytes
	physical_volumes {
		pv0 {
			id = "AAAAAA-BBBB-CCCC-DDDD-EEEE-FFFF-GGGGGG"
			device = "/dev/sda3"	# Hint only
			pe_start = 2048
			pe_count = 100
		}
	}
	logical_volumes {
		ubuntu-lv {
			segment_count = 2
			segment1 {
				start_extent = 0
				extent_count = 10
				type = "striped"
				stripe_count = 1
				stripes = [
					"pv0", 5
				]
			}
			segment2 {
				start_extent = 10
				extent_count = 2
				type = "striped"
				stripe_count = 1
				stripes = [
					"pv0", 50
				]
			}
		}
		thin {
			segment_count = 1
			segment1 {
				start_extent = 0
				extent_count = 1
				type = "thin"
			}
		}
	}
}
`

func TestLVMConfig(t *testing.T) {
	cfg, err := parseLVMConfig(vgText)
	if err != nil {
		t.Fatal(err)
	}
	vg := cfg["ubuntu-vg"].(map[string]any)
	if toInt(vg["extent_size"]) != 8192 {
		t.Fatalf("extent size %v", vg["extent_size"])
	}
	lv := vg["logical_volumes"].(map[string]any)["ubuntu-lv"].(map[string]any)
	stripes := lv["segment2"].(map[string]any)["stripes"].([]any)
	if stripes[0] != "pv0" || toInt(stripes[1]) != 50 {
		t.Fatalf("stripes %v", stripes)
	}
}

func TestLVReader(t *testing.T) {
	pv := make([]byte, 64)
	for i := range pv {
		pv[i] = byte(i)
	}
	// Two segments of 8 bytes: LV 0-7 -> PV 40-47, LV 8-15 -> PV 8-15.
	l := &lvReader{pv: bytes.NewReader(pv), segs: []segment{{0, 8, 40}, {8, 8, 8}}, size: 16}
	b := make([]byte, 16)
	if n, err := l.ReadAt(b, 0); n != 16 || err != nil {
		t.Fatalf("read %d %v", n, err)
	}
	if b[0] != 40 || b[7] != 47 || b[8] != 8 || b[15] != 15 {
		t.Fatalf("mapping wrong: %v", b)
	}
	if _, err := l.ReadAt(b, 10); err != io.EOF {
		t.Fatalf("read past end: %v", err)
	}
}

func TestMBRLogical(t *testing.T) {
	disk := make([]byte, 4<<20)
	put := func(off int, i int, typ byte, start, n uint32) {
		e := disk[off+446+16*i:]
		e[4] = typ
		binary.LittleEndian.PutUint32(e[8:], start)
		binary.LittleEndian.PutUint32(e[12:], n)
		disk[off+510], disk[off+511] = 0x55, 0xAA
	}
	put(0, 0, 0x83, 2048, 2048)        // p1: 1 MiB at 1 MiB
	put(0, 1, 0x05, 4096, 4096)        // extended at 2 MiB
	put(4096*512, 0, 0x83, 2048, 1024) // p5 at 2 MiB + 1 MiB
	put(4096*512, 1, 0x05, 3072, 1024) // next EBR at extended + 1.5 MiB
	put((4096+3072)*512, 0, 0x82, 64, 512)
	vols, err := Volumes(bytes.NewReader(disk), int64(len(disk)))
	if err != nil {
		t.Fatal(err)
	}
	var ids []string
	for _, v := range vols {
		ids = append(ids, v.ID)
	}
	if len(vols) != 3 || ids[0] != "p1" || ids[1] != "p5" || ids[2] != "p6" {
		t.Fatalf("volumes %v", ids)
	}
	if vols[1].Offset != (4096+2048)*512 || vols[2].Offset != (4096+3072+64)*512 {
		t.Fatalf("offsets %d %d", vols[1].Offset, vols[2].Offset)
	}
}

func TestClean(t *testing.T) {
	for in, want := range map[string]string{"": "/", "etc": "/etc", `\Users\ana`: "/Users/ana", "/a/../../b": "/b"} {
		if got := Clean(in); got != want {
			t.Errorf("Clean(%q) = %q", in, got)
		}
	}
}

// linkFS is a file system like the ext4 reader: Stat does not follow
// symbolic links, ReadLink returns their targets.
type linkFS struct {
	files map[string]string
	links map[string]string
	dirs  map[string]bool
}

type linkInfo struct {
	name string
	size int64
	mode fs.FileMode
}

func (i linkInfo) Name() string       { return path.Base(i.name) }
func (i linkInfo) Size() int64        { return i.size }
func (i linkInfo) Mode() fs.FileMode  { return i.mode }
func (i linkInfo) ModTime() time.Time { return time.Time{} }
func (i linkInfo) IsDir() bool        { return i.mode.IsDir() }
func (i linkInfo) Sys() any           { return nil }

func (l linkFS) Stat(name string) (fs.FileInfo, error) {
	if t, ok := l.links[name]; ok {
		return linkInfo{name, int64(len(t)), fs.ModeSymlink}, nil
	}
	if d, ok := l.files[name]; ok {
		return linkInfo{name, int64(len(d)), 0}, nil
	}
	if l.dirs[name] {
		return linkInfo{name, 0, fs.ModeDir}, nil
	}
	return nil, fs.ErrNotExist
}

func (l linkFS) Open(name string) (fs.File, error) {
	if d, ok := l.files[name]; ok {
		return fstest.MapFS{name: {Data: []byte(d)}}.Open(name)
	}
	if _, ok := l.links[name]; ok {
		return fstest.MapFS{name: {}}.Open(name) // the raw link reads as empty
	}
	return nil, fs.ErrNotExist
}

func (l linkFS) ReadLink(name string) (string, error) {
	if t, ok := l.links[name]; ok {
		return t, nil
	}
	return "", fs.ErrInvalid
}

// Symbolic links are read as the files they point to: relative and
// absolute targets, chains, and loops end with an error.
func TestSymlinks(t *testing.T) {
	f := &ioFS{fsys: linkFS{
		files: map[string]string{"usr/lib/os-release": "ID=debian\n", "srv/data/f1.bin": "one"},
		dirs:  map[string]bool{"usr": true, "usr/lib": true, "etc": true, "srv": true, "srv/data": true},
		links: map[string]string{"etc/os-release": "../usr/lib/os-release", "srv/abs": "/srv/data/f1.bin",
			"srv/chain": "abs", "srv/loop1": "loop2", "srv/loop2": "loop1", "srv/datadir": "data", "srv/win": `\srv\data\f1.bin`},
	}}
	for p, want := range map[string]string{"/etc/os-release": "ID=debian\n", "/srv/abs": "one", "/srv/chain": "one", "/srv/win": "one"} {
		r, n, err := f.ReadFile(p)
		if err != nil {
			t.Errorf("%s: %v", p, err)
			continue
		}
		b, _ := io.ReadAll(r)
		if string(b) != want || n != int64(len(want)) {
			t.Errorf("%s: %q (%d)", p, b, n)
		}
	}
	if e, err := f.Stat("/etc/os-release"); err != nil || e.IsDir || e.Size != 10 || e.Path != "/etc/os-release" {
		t.Errorf("stat: %+v %v", e, err)
	}
	if e, err := f.Stat("/srv/datadir"); err != nil || !e.IsDir {
		t.Errorf("link to folder: %+v %v", e, err)
	}
	if _, _, err := f.ReadFile("/srv/loop1"); err == nil || !strings.Contains(err.Error(), "too many levels") {
		t.Errorf("loop: %v", err)
	}
}
